# Generated by Django 4.0.3 on 2024-01-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
