# Generated by Django 4.0.3 on 2024-01-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0003_rename_product_cartitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
