# Generated by Django 4.0.3 on 2024-01-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
